### ISSUE TITLE
Allow access to raw data

### ISSUE THREAD

**Issue by emersion** [luksen/maildir#6]
1. Some frontends like IMAP allow access to a range of the raw message. It's not possible to implement this feature if we only have access to a `mail.Message`
2. Because of the way `net/mail` handles whitespace and doesn't keep header fields in the original order, it breaks DKIM

I'd even prefer not to expose `mail.Message` and `mail.Header` at all - there are alternative mail libraries, and getting a `mail.Message` from an `io.Reader` is just one function call away.

**Comment by luksen** [comment]
You are correct, replacing Message and Header with a single function that returns a Reader would be better design.

**Comment by emersion** [comment]
Just FYI, since I opened this issue I forked this library into https://github.com/emersion/go-maildir.

**Comment by luksen** [comment]
I've been mulling this over for a bit and I don't think I'll be adding this after all. Mainly because it's easy to get a reader from the filename. I'll close this issue but feel free to comment anyways if you have additional input.
